version: "3"

services:
  cloudflared:
    container_name: cloudflared
    image: visibilityspots/cloudflared:latest
    restart: unless-stopped
    networks:
      pihole_net:
        ipv4_address: 10.0.0.2

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
    environment:
      - FTLCONF_REPLY_ADDR4=10.0.0.3
      - PIHOLE_DNS_=10.0.0.2#5054
      - IPv6=false
      - TZ=America/Toronto
      - DNSMASQ_LISTENING=all
      - WEBPASSWORD=*****YOUR_PASSWORD_HERE*****
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    networks:
      pihole_net:
        ipv4_address: 10.0.0.3
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN

networks:
  pihole_net:
    name: pi_net
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/29
